Add activatorCapacity as a configurable variable to the knative helmchart
mesosphere/charts pull request #1324
Opened 2022-05-20 01:38 UTC by timcharper

Also, I add the makevar REPO_URL to allow for hosting the charts in a
local http server, such as caddy.

2022-05-23 08:44 UTC, timcharper commented on Makefile
> +REPO_URL := https://$(GITHUB_USER).github.io/charts
Maybe this would be better named REPO_BASE_URL ?

2022-05-26 19:33 UTC, timcharper commented
@gracedo this PR does not update the component version. Should I add a `-1` to the end of the chart version, to confer a packaging change only?

2022-06-08 22:52 UTC, gracedo commented
@timcharper sorry I completely missed this - can we bump the chart version? This looks like it's adding functionality to to the helm chart modify values, which justifies a chart bump

2022-06-13 16:35 UTC, lukeogg approved these changes
LGTM!

2022-06-13 23:00 UTC, andresmascl approved these changes
Looks good to me too!

2022-06-13 23:02 UTC, gracedo requested changes
needs a chart version bump, please

2022-06-14 02:29 UTC, timcharper commented
> needs a chart version bump, please

How to we bump the chart version? `-1` suffix or something?

2022-06-14 02:31 UTC, gracedo commented
https://github.com/mesosphere/charts/blob/tharper/knative-activator-capacity/staging/knative/Chart.yaml#L3
This should be bumped to maybe 0.4.0 since it's adding new functionality

2022-06-14 07:14 UTC, juliangieseke commented
I think https://github.com/mesosphere/charts/blob/tharper/knative-activator-capacity/staging/knative/charts/serving/Chart.yaml#L3 needs a bump too.

2022-07-14 18:19 UTC, gracedo approved these changes

2022-07-14 18:19 UTC, merged