[auto-cluster] chore: update flag `max-node-provision-time`
mesosphere/charts pull request #782
Opened 2020-09-03 22:03 UTC by alejandroEsc

**What type of PR is this?**

Chore

**What this PR does/ why we need it**:

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/D2IQ-71471

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
max provision time set to 1h by default 
```

**Checklist**

* [ ] *If a chart is changed, the chart version is correctly incremented.*
* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

2020-09-04 01:06 UTC, samvantran reviewed
This is a public repo, let's stick to comments that help the user understand the config and have the conversation around what we _should_ do internal to the company.

2020-09-04 01:06 UTC, samvantran commented on stable/cluster-autoscaler/values.yaml
> +  # least and we should have metrics that alert the user when this thresh-hold of an hour is hit.
```suggestion
  # The maximum amount of time cluster-autoscaler will attempt to provision a new node.
```

2020-09-04 02:50 UTC, alejandroEsc commented on stable/cluster-autoscaler/values.yaml
> +  # least and we should have metrics that alert the user when this thresh-hold of an hour is hit.
sure thing.

2020-09-04 04:59 UTC, samvantran approved these changes

2020-09-04 11:19 UTC, shaneutt approved these changes

2020-09-04 11:19 UTC, shaneutt commented on stable/cluster-autoscaler/values.yaml
> +  # Maximum time from last recorded successful autoscaler run before automatic restart
Thanks for documenting this one too while you're at it.

2020-09-04 14:22 UTC, armandgrillet approved these changes

2020-09-04 17:37 UTC, hectorj2f requested changes
Please, let's justify this change before applying it. I understood we agreed on spotting this scenario in the logs first.

2020-09-08 17:14 UTC, alejandroEsc commented
> Please, let's justify this change before applying it. I understood we agreed on spotting this scenario in the logs first.

This is why I placed it in do not merge. I wanted to also conduct some testing with this change.

2020-09-08 17:16 UTC, hectorj2f commented
@alejandroEsc I think it was a mismatch in terms of timing about these comments, 👍🏻 .

2020-09-28 22:37 UTC, alejandroEsc commented
closing for now.

2020-09-28 22:37 UTC, closed without merging