Do kommander catlog api bumps to kommander chart
mesosphere/charts pull request #901
Opened 2020-11-17 21:11 UTC by faiq

**What type of PR is this?**

**What this PR does/ why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

* [ ] *If a chart is changed, the chart version is correctly incremented.*
* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

2020-11-17 21:11 UTC, faiq commented
/bump-catalog

2020-11-17 21:46 UTC, faiq commented
/bump-catalog

2020-11-17 21:54 UTC, faiq commented
/bump-catalog

2020-11-17 22:05 UTC, faiq commented
/bump-catalog

2020-11-17 23:34 UTC, faiq commented
/bump-catalog

2020-11-18 00:17 UTC, faiq commented
/bump-catalog

2020-11-18 00:21 UTC, faiq commented
/bump-catalog

2020-11-18 00:24 UTC, faiq commented
/bump-catalog

2020-11-18 00:27 UTC, faiq commented
/bump-catalog

2020-11-18 00:34 UTC, faiq commented
/bump-catalog

2020-11-18 00:37 UTC, faiq commented
/bump-catalog

2020-11-18 21:18 UTC, faiq commented
/bump-catalog

2020-11-18 21:23 UTC, faiq commented
/bump-catalog

2020-11-18 22:19 UTC, joejulian approved these changes

2020-11-18 23:40 UTC, cprovencher requested changes

2020-11-18 23:40 UTC, cprovencher commented on Dispatchfile
> +  git config --local user.name 'Dispatch CI'
missing GPG stuff to sign the commits

2020-11-18 23:42 UTC, cprovencher commented on Dispatchfile
> +  command=["/bin/sh", "-c"], args=[
I like the idea of passing the args here

2020-11-19 01:15 UTC, faiq commented
/bump-catalog

2020-11-19 01:48 UTC, cprovencher approved these changes

2020-11-19 01:49 UTC, merged