fix: do not patch webhook
mesosphere/charts pull request #919
Opened 2020-12-06 18:11 UTC by jr0d

**What type of PR is this?**

Bug

**What this PR does/ why we need it**:

Allow upgrades to succeed without intervention when kommander is disabled

**Which issue(s) this PR fixes**:

no issue

**Special notes for your reviewer**:
This "fix" for the authorized lister aggregated API should not be needed as kommander should update the service with the correct API group: https://github.com/mesosphere/yakcl/blob/master/chart/kommander-federation/templates/apiservice_authorizedlister.yaml#L5

The reason we added this fix was we were seeing some inconsistent behaviour where  the old apigroup for cert-manager was still present after the kommander upgrade. If we continue to see this behaviour, a fix should be made to the kommander chart. 
 
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Checklist**

* [ ] *If a chart is changed, the chart version is correctly incremented.*
* [ ] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

2020-12-07 22:06 UTC, branden requested changes

2020-12-07 22:06 UTC, branden commented on stable/cert-manager-setup/Chart.yaml
>  version: 0.2.6
```suggestion
version: 0.2.7
```

2020-12-08 00:06 UTC, branden approved these changes

2020-12-08 01:09 UTC, joejulian approved these changes

2020-12-08 01:35 UTC, merged